trigger: none
pr: none

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: Maven@3
  inputs:
    jdkVersionOption: '1.8'
    publishJUnitResults: true
    goals: 'clean test'
    options: '-Pintegration'
- task: DownloadSecureFile@1
  displayName: 'Download Maven master password'
  name: mavenSecurity
  inputs:
    secureFile: settings-security.xml
- task: DownloadSecureFile@1
  displayName: 'Download settings.xml'
  name: mavenSettings
  inputs:
    secureFile: settings.xml
- task: DownloadSecureFile@1
  displayName: 'Download pgp key'
  name: secretKey
  inputs:
    secureFile: secret_key.asc

# Set version to non-snapshot
- powershell: |
    & "./scripts/unsetSnapshot.ps1"

# Publish jars
- script: |
    mv $(mavenSecurity.secureFilePath) ~/.m2
    mvn clean deploy -Prelease -s $(mavenSettings.secureFilePath) -B -U \
      -Dpgp.secretkey=keyfile:$(secretKey.secureFilePath) \
      -Dpgp.passphrase=literal:$(PGP_PASSPHRASE) \
      -DskipTests=true

# Build package
- script:
    mvn clean package

# Upload to Azure downloadarchive
- powershell: |
    $version = invoke-expression -Command "./scripts/getRevision.ps1"
    az login --service-principal -u http://OpenValidationServicePrincipal -p $(AZURE_SP_KEY) --tenant brockhausag.onmicrosoft.com
    az storage blob upload --acount-name downloadarchive -c openvalidation-generator -f "./target/openvalidation.jar" -n "openvalidation.jar"
    az storage blob upload --acount-name downloadarchive -c openvalidation-generator -f "./target/openvalidation.jar" -n "$($version)/openvalidation.jar"
